# Constraint: Cấm runAsUser: 0 (chạy root)
# Áp dụng cho Rollout, Deployment, StatefulSet, DaemonSet
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ForbidRootUser
metadata:
  name: no-runasroot
spec:
  match:
    kinds:
      - apiGroups: ["argoproj.io"]
        kinds: ["Rollout"]
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet", "DaemonSet"]
    excludedNamespaces:
      - kube-system
      - gatekeeper-system
