apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-db-password
  namespace: demo
  labels:
    owner: hailv
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: api-db-secret
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          owner: hailv
  data:
    - secretKey: password
      remoteRef:
        key: w10/lab2/db
        property: password
