apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: demo
  labels:
    owner: hailv
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secretsmanager-credentials
            key: access-key-id
          secretAccessKeySecretRef:
            name: aws-secretsmanager-credentials
            key: secret-access-key
